services:
  - type: worker
    name: tkrs-bot
    runtime: python
    repo: https://github.com/rajek751-rgb/TKRS_Replitbot.git
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false  # Будет запрошено при деплое
      - key: TELEGRAM_GROUP_ID
        sync: false  # Будет запрошено при деплое
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1