services:
  - type: worker
    name: tkrs-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_ID
        sync: false